name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  conformance:
    name: Conformance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Prettier
        run: npm run prettier -- --list-different

      - name: Typecheck
        run: npm run typecheck
